// data.ts

export type FAQItem = {
	id: number;
	question: string;
	answer: string;
};

export const faqs: FAQItem[] = [
	{
		id: 1,
		question: 'What is ZipLinkz?',
		answer:
			'ZipLinkz is a URL shortening service that allows users to create short, memorable links for sharing on social media, emails, and other platforms.',
	},
	{
		id: 2,
		question: 'How does ZipLinkz work?',
		answer:
			"To use ZipLinkz, simply paste your long URL into the provided input field on the homepage and click the 'Shorten' button. ZipLinkz will generate a shortened URL that you can copy and share.",
	},
	{
		id: 3,
		question: 'Is ZipLinkz free to use?',
		answer:
			'Yes, ZipLinkz offers a free plan that allows users to shorten URLs and access basic analytics. Additionally, ZipLinkz offers premium plans with advanced features for users with higher usage needs.',
	},
	{
		id: 4,
		question: 'Can I customize my shortened URLs?',
		answer:
			'Yes, ZipLinkz allows users to customize their shortened URLs with custom aliases. This feature is available in premium plans.',
	},
	{
		id: 5,
		question: 'Is there a limit to the number of URLs I can shorten?',
		answer:
			'ZipLinkz offers different plans with varying limits on the number of URLs you can shorten. The free plan has a limit of 100 shortened URLs per month, while premium plans offer higher limits.',
	},
	{
		id: 6,
		question: 'How long are the shortened URLs?',
		answer:
			'Shortened URLs generated by ZipLinkz are typically around 6-8 characters long. This ensures that they are short and easy to share while still being unique.',
	},
	{
		id: 7,
		question: 'Can I track analytics for my shortened URLs?',
		answer:
			'Yes, ZipLinkz provides detailed analytics for shortened URLs, including the number of clicks, geographic location of users, referral sources, and more. This feature is available in premium plans.',
	},
	{
		id: 8,
		question: 'How secure are the shortened URLs?',
		answer:
			'ZipLinkz takes security seriously and ensures that all shortened URLs are secure and safe to use. Additionally, premium plans offer advanced security features such as password protection and expiration dates.',
	},
	{
		id: 9,
		question: 'Can I edit or delete shortened URLs?',
		answer:
			'Yes, ZipLinkz allows users to edit or delete shortened URLs from their account dashboard. This feature is available to all users, regardless of their plan.',
	},
	{
		id: 10,
		question: 'How can I contact support?',
		answer:
			'If you have any questions or need assistance, you can contact ZipLinkz support through the contact form on the website or by emailing support@ziplinkz.com. Our support team is available 24/7 to assist you.',
	},
];
